branches:
  - main
tagFormat: ${version}
plugins:
  - [
      "@semantic-release/commit-analyzer",
      {
        preset: "conventionalcommits",
        releaseRules:
          [
            { type: "minor", release: "minor" },
            { type: "feat", release: "patch" },
            { type: "impr", release: "patch" },
            { type: "refactor", release: "patch" },
            { type: "perf", release: "patch" },
            { type: "fix", release: "patch" },
            { type: "ci", release: "patch" },
            { type: "docs", release: "patch" },
            { type: "chore", release: "patch" },
            { type: "style", release: "patch" },
            { type: "test", release: "patch" },
            { type: "build", release: "patch" },
          ],
      },
    ]
  - [
      "@semantic-release/release-notes-generator",
      {
        preset: "conventionalcommits",
        presetConfig:
          {
            types:
              [
                { type: "minor", section: "🎯 Minor Release" },
                { type: "feat", section: "✨ Features" },
                { type: "impr", section: "🚀 Improvements" },
                { type: "refactor", section: "♻️ Improvements" },
                { type: "perf", section: "⚡️ Improvements" },
                { type: "build", section: "📦 Improvements" },
                { type: "fix", section: "🐛 Bug Fixes" },
                { type: "ci", section: "👷 CI" },
                { type: "docs", section: "📚 Documentation" },
                { type: "chore", section: "🔧 Miscellaneous" },
                { type: "style", section: "🎨 Miscellaneous" },
                { type: "test", section: "✅ Miscellaneous" },
              ],
          },
      },
    ]
  - [
      "@semantic-release/exec",
      {
        "prepareCmd": "sed -i 's/^version = .*$/version = \"${nextRelease.version}\"/' config/shared.toml && sed -i 's/MLODA_REGISTRY_VERSION:[0-9.]\\+}/MLODA_REGISTRY_VERSION:${nextRelease.version}}/g' tox.ini && python scripts/generate_pyproject.py",
      },
    ]
  - [
      "@semantic-release/github",
      {
        "releaseNameTemplate": "🚀 Version ${nextRelease.version}",
        "successComment": false,
        "releasedLabels": false,
        "failComment": false,
      },
    ]
  - [
      "@semantic-release/git",
      {
        "assets": [
          "config/shared.toml",
          "**/pyproject.toml",
          "tox.ini"
        ]
      },
    ]
repositoryUrl: "https://github.com/mloda-ai/mloda-registry"
