"""PythonDict implementation for string operation feature groups."""

from __future__ import annotations

from typing import Any

from mloda.provider import ComputeFramework
from mloda_plugins.compute_framework.base_implementations.python_dict.python_dict_framework import (
    PythonDictFramework,
)

from mloda.community.feature_groups.data_operations.string.base import (
    StringFeatureGroup,
)

# PyArrow's ``pc.utf8_upper``/``pc.utf8_lower`` apply Unicode's SIMPLE,
# context-free, per-codepoint case mapping (``UnicodeData.txt``'s simple
# mapping field). Python's ``str.upper()``/``str.lower()`` apply Unicode's
# FULL case mapping, which additionally layers on the small, closed set of
# UNCONDITIONAL entries from ``SpecialCasing.txt``: codepoints where the
# "full" mapping expands to more than one character (e.g. German sharp s
# "ß" -> "SS") or otherwise differs from the codepoint's own simple
# mapping (e.g. Turkish dotted capital I "İ" -> "i" + combining dot
# above, U+0307).
#
# The two tables below cover that closed set, plus a second, unrelated source of
# per-codepoint drift: PyArrow bundles utf8proc, whose Unicode Character Database
# version can be newer than the CPython interpreter's own bundled `unicodedata`, so a
# very recently assigned codepoint can have a case mapping in PyArrow's simple mapping
# before Python's `.upper()`/`.lower()` know about it at all (see the drift test in
# string/tests/test_python_dict.py, which scans range(0x110000) against a live PyArrow
# build, so either source of drift fails a test instead of reappearing silently).
# Processing per character (see ``_upper``/``_lower`` below) and consulting these tables
# first, falling back to Python's own single-character ``.upper()``/``.lower()``
# otherwise, reproduces PyArrow's simple mapping for every other codepoint too,
# including context-dependent full-mapping rules like Greek final sigma
# (``Σ`` -> ``ς`` only at the end of a word), which never trigger
# on a single-character Python call and therefore never apply here.
_UPPER_OVERRIDES: dict[str, str] = {
    "ß": "ẞ",  # LATIN SMALL LETTER SHARP S -> LATIN CAPITAL LETTER SHARP S
    "ŉ": "ŉ",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE -> LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
    "ǰ": "ǰ",  # LATIN SMALL LETTER J WITH CARON -> LATIN SMALL LETTER J WITH CARON
    "ΐ": "ΐ",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS -> GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    "ΰ": "ΰ",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS -> GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
    "և": "և",  # ARMENIAN SMALL LIGATURE ECH YIWN -> ARMENIAN SMALL LIGATURE ECH YIWN
    "ẖ": "ẖ",  # LATIN SMALL LETTER H WITH LINE BELOW -> LATIN SMALL LETTER H WITH LINE BELOW
    "ẗ": "ẗ",  # LATIN SMALL LETTER T WITH DIAERESIS -> LATIN SMALL LETTER T WITH DIAERESIS
    "ẘ": "ẘ",  # LATIN SMALL LETTER W WITH RING ABOVE -> LATIN SMALL LETTER W WITH RING ABOVE
    "ẙ": "ẙ",  # LATIN SMALL LETTER Y WITH RING ABOVE -> LATIN SMALL LETTER Y WITH RING ABOVE
    "ẚ": "ẚ",  # LATIN SMALL LETTER A WITH RIGHT HALF RING -> LATIN SMALL LETTER A WITH RIGHT HALF RING
    "ὐ": "ὐ",  # GREEK SMALL LETTER UPSILON WITH PSILI -> GREEK SMALL LETTER UPSILON WITH PSILI
    "ὒ": "ὒ",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA -> GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
    "ὔ": "ὔ",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA -> GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
    "ὖ": "ὖ",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI -> GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
    "ᾀ": "ᾈ",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
    "ᾁ": "ᾉ",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
    "ᾂ": "ᾊ",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾃ": "ᾋ",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾄ": "ᾌ",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾅ": "ᾍ",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾆ": "ᾎ",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾇ": "ᾏ",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾈ": "ᾈ",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
    "ᾉ": "ᾉ",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
    "ᾊ": "ᾊ",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾋ": "ᾋ",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾌ": "ᾌ",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾍ": "ᾍ",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾎ": "ᾎ",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾏ": "ᾏ",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾐ": "ᾘ",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
    "ᾑ": "ᾙ",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
    "ᾒ": "ᾚ",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾓ": "ᾛ",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾔ": "ᾜ",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾕ": "ᾝ",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾖ": "ᾞ",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾗ": "ᾟ",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾘ": "ᾘ",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
    "ᾙ": "ᾙ",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
    "ᾚ": "ᾚ",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾛ": "ᾛ",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾜ": "ᾜ",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾝ": "ᾝ",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾞ": "ᾞ",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾟ": "ᾟ",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾠ": "ᾨ",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
    "ᾡ": "ᾩ",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
    "ᾢ": "ᾪ",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾣ": "ᾫ",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾤ": "ᾬ",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾥ": "ᾭ",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾦ": "ᾮ",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾧ": "ᾯ",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾨ": "ᾨ",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
    "ᾩ": "ᾩ",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
    "ᾪ": "ᾪ",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    "ᾫ": "ᾫ",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    "ᾬ": "ᾬ",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    "ᾭ": "ᾭ",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    "ᾮ": "ᾮ",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾯ": "ᾯ",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
    "ᾲ": "ᾲ",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
    "ᾳ": "ᾼ",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
    "ᾴ": "ᾴ",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
    "ᾶ": "ᾶ",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI -> GREEK SMALL LETTER ALPHA WITH PERISPOMENI
    "ᾷ": "ᾷ",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI -> GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
    "ᾼ": "ᾼ",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI -> GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
    "ῂ": "ῂ",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
    "ῃ": "ῌ",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
    "ῄ": "ῄ",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
    "ῆ": "ῆ",  # GREEK SMALL LETTER ETA WITH PERISPOMENI -> GREEK SMALL LETTER ETA WITH PERISPOMENI
    "ῇ": "ῇ",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI -> GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
    "ῌ": "ῌ",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI -> GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
    "ῒ": "ῒ",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA -> GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
    "ΐ": "ΐ",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA -> GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
    "ῖ": "ῖ",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI -> GREEK SMALL LETTER IOTA WITH PERISPOMENI
    "ῗ": "ῗ",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI -> GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
    "ῢ": "ῢ",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA -> GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
    "ΰ": "ΰ",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA -> GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
    "ῤ": "ῤ",  # GREEK SMALL LETTER RHO WITH PSILI -> GREEK SMALL LETTER RHO WITH PSILI
    "ῦ": "ῦ",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI -> GREEK SMALL LETTER UPSILON WITH PERISPOMENI
    "ῧ": "ῧ",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI -> GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
    "ῲ": "ῲ",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
    "ῳ": "ῼ",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
    "ῴ": "ῴ",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI -> GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
    "ῶ": "ῶ",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI -> GREEK SMALL LETTER OMEGA WITH PERISPOMENI
    "ῷ": "ῷ",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI -> GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
    "ῼ": "ῼ",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI -> GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
    "ﬀ": "ﬀ",  # LATIN SMALL LIGATURE FF -> LATIN SMALL LIGATURE FF
    "ﬁ": "ﬁ",  # LATIN SMALL LIGATURE FI -> LATIN SMALL LIGATURE FI
    "ﬂ": "ﬂ",  # LATIN SMALL LIGATURE FL -> LATIN SMALL LIGATURE FL
    "ﬃ": "ﬃ",  # LATIN SMALL LIGATURE FFI -> LATIN SMALL LIGATURE FFI
    "ﬄ": "ﬄ",  # LATIN SMALL LIGATURE FFL -> LATIN SMALL LIGATURE FFL
    "ﬅ": "ﬅ",  # LATIN SMALL LIGATURE LONG S T -> LATIN SMALL LIGATURE LONG S T
    "ﬆ": "ﬆ",  # LATIN SMALL LIGATURE ST -> LATIN SMALL LIGATURE ST
    "ﬓ": "ﬓ",  # ARMENIAN SMALL LIGATURE MEN NOW -> ARMENIAN SMALL LIGATURE MEN NOW
    "ﬔ": "ﬔ",  # ARMENIAN SMALL LIGATURE MEN ECH -> ARMENIAN SMALL LIGATURE MEN ECH
    "ﬕ": "ﬕ",  # ARMENIAN SMALL LIGATURE MEN INI -> ARMENIAN SMALL LIGATURE MEN INI
    "ﬖ": "ﬖ",  # ARMENIAN SMALL LIGATURE VEW NOW -> ARMENIAN SMALL LIGATURE VEW NOW
    "ﬗ": "ﬗ",  # ARMENIAN SMALL LIGATURE MEN XEH -> ARMENIAN SMALL LIGATURE MEN XEH
    # Unicode-version-lag entries (unnamed in this interpreter's `unicodedata`; written
    # as escapes rather than literal glyphs since not every font/terminal has them yet).
    "꟏": "꟎",  # U+A7CF -> U+A7CE
    "ꟓ": "꟒",  # U+A7D3 -> U+A7D2
    "ꟕ": "꟔",  # U+A7D5 -> U+A7D4
    "\U00016ebb": "\U00016ea0",  # U+16EBB -> U+16EA0
    "\U00016ebc": "\U00016ea1",  # U+16EBC -> U+16EA1
    "\U00016ebd": "\U00016ea2",  # U+16EBD -> U+16EA2
    "\U00016ebe": "\U00016ea3",  # U+16EBE -> U+16EA3
    "\U00016ebf": "\U00016ea4",  # U+16EBF -> U+16EA4
    "\U00016ec0": "\U00016ea5",  # U+16EC0 -> U+16EA5
    "\U00016ec1": "\U00016ea6",  # U+16EC1 -> U+16EA6
    "\U00016ec2": "\U00016ea7",  # U+16EC2 -> U+16EA7
    "\U00016ec3": "\U00016ea8",  # U+16EC3 -> U+16EA8
    "\U00016ec4": "\U00016ea9",  # U+16EC4 -> U+16EA9
    "\U00016ec5": "\U00016eaa",  # U+16EC5 -> U+16EAA
    "\U00016ec6": "\U00016eab",  # U+16EC6 -> U+16EAB
    "\U00016ec7": "\U00016eac",  # U+16EC7 -> U+16EAC
    "\U00016ec8": "\U00016ead",  # U+16EC8 -> U+16EAD
    "\U00016ec9": "\U00016eae",  # U+16EC9 -> U+16EAE
    "\U00016eca": "\U00016eaf",  # U+16ECA -> U+16EAF
    "\U00016ecb": "\U00016eb0",  # U+16ECB -> U+16EB0
    "\U00016ecc": "\U00016eb1",  # U+16ECC -> U+16EB1
    "\U00016ecd": "\U00016eb2",  # U+16ECD -> U+16EB2
    "\U00016ece": "\U00016eb3",  # U+16ECE -> U+16EB3
    "\U00016ecf": "\U00016eb4",  # U+16ECF -> U+16EB4
    "\U00016ed0": "\U00016eb5",  # U+16ED0 -> U+16EB5
    "\U00016ed1": "\U00016eb6",  # U+16ED1 -> U+16EB6
    "\U00016ed2": "\U00016eb7",  # U+16ED2 -> U+16EB7
    "\U00016ed3": "\U00016eb8",  # U+16ED3 -> U+16EB8
}

_LOWER_OVERRIDES: dict[str, str] = {
    "İ": "i",  # LATIN CAPITAL LETTER I WITH DOT ABOVE -> LATIN SMALL LETTER I
    # Unicode-version-lag entries; see the matching comment on _UPPER_OVERRIDES above.
    "꟎": "꟏",  # U+A7CE -> U+A7CF
    "꟒": "ꟓ",  # U+A7D2 -> U+A7D3
    "꟔": "ꟕ",  # U+A7D4 -> U+A7D5
    "\U00016ea0": "\U00016ebb",  # U+16EA0 -> U+16EBB
    "\U00016ea1": "\U00016ebc",  # U+16EA1 -> U+16EBC
    "\U00016ea2": "\U00016ebd",  # U+16EA2 -> U+16EBD
    "\U00016ea3": "\U00016ebe",  # U+16EA3 -> U+16EBE
    "\U00016ea4": "\U00016ebf",  # U+16EA4 -> U+16EBF
    "\U00016ea5": "\U00016ec0",  # U+16EA5 -> U+16EC0
    "\U00016ea6": "\U00016ec1",  # U+16EA6 -> U+16EC1
    "\U00016ea7": "\U00016ec2",  # U+16EA7 -> U+16EC2
    "\U00016ea8": "\U00016ec3",  # U+16EA8 -> U+16EC3
    "\U00016ea9": "\U00016ec4",  # U+16EA9 -> U+16EC4
    "\U00016eaa": "\U00016ec5",  # U+16EAA -> U+16EC5
    "\U00016eab": "\U00016ec6",  # U+16EAB -> U+16EC6
    "\U00016eac": "\U00016ec7",  # U+16EAC -> U+16EC7
    "\U00016ead": "\U00016ec8",  # U+16EAD -> U+16EC8
    "\U00016eae": "\U00016ec9",  # U+16EAE -> U+16EC9
    "\U00016eaf": "\U00016eca",  # U+16EAF -> U+16ECA
    "\U00016eb0": "\U00016ecb",  # U+16EB0 -> U+16ECB
    "\U00016eb1": "\U00016ecc",  # U+16EB1 -> U+16ECC
    "\U00016eb2": "\U00016ecd",  # U+16EB2 -> U+16ECD
    "\U00016eb3": "\U00016ece",  # U+16EB3 -> U+16ECE
    "\U00016eb4": "\U00016ecf",  # U+16EB4 -> U+16ECF
    "\U00016eb5": "\U00016ed0",  # U+16EB5 -> U+16ED0
    "\U00016eb6": "\U00016ed1",  # U+16EB6 -> U+16ED1
    "\U00016eb7": "\U00016ed2",  # U+16EB7 -> U+16ED2
    "\U00016eb8": "\U00016ed3",  # U+16EB8 -> U+16ED3
}


def _upper(value: str) -> str:
    return "".join(_UPPER_OVERRIDES.get(ch, ch.upper()) for ch in value)


def _lower(value: str) -> str:
    return "".join(_LOWER_OVERRIDES.get(ch, ch.lower()) for ch in value)


class PythonDictStringOps(StringFeatureGroup):
    @classmethod
    def compute_framework_rule(cls) -> set[type[ComputeFramework]] | None:
        return {PythonDictFramework}

    @classmethod
    def _compute_string(
        cls,
        data: dict[str, list[Any]],
        feature_name: str,
        source_col: str,
        op: str,
    ) -> dict[str, list[Any]]:
        col = data[source_col]

        result: list[Any]
        if op == "upper":
            result = [None if v is None else _upper(v) for v in col]
        elif op == "lower":
            result = [None if v is None else _lower(v) for v in col]
        elif op == "trim":
            result = [None if v is None else v.strip() for v in col]
        elif op == "length":
            result = [None if v is None else len(v) for v in col]
        elif op == "reverse":
            result = [None if v is None else v[::-1] for v in col]
        else:
            raise ValueError(f"Unsupported string operation: {op}")

        data = dict(data)
        data[feature_name] = result
        return data
