"""Enterprise Audit Extender package."""

from mloda.enterprise.extenders.audit.audit_extender import (
    AuditExtender,
    AuditSink,
    IdentityRequiredError,
    NdjsonAuditSink,
    TeeAuditSink,
)
from mloda.enterprise.extenders.audit.run_manifest import (
    Ed25519Signer,
    HmacSha256Signer,
    KeyAlreadyCurrentError,
    LogCoverage,
    ManifestSigner,
    ManifestVerificationError,
    QuarantinedLine,
    RunAlreadySealedError,
    RunNotPendingError,
    manifest_hash,
    quarantine_damaged_lines,
    rotate_manifest_key,
    seal_ndjson_runs,
    seal_run,
    verify_manifest,
    verify_ndjson_log,
    verify_ndjson_log_coverage,
)

__all__ = [
    "AuditExtender",
    "AuditSink",
    "Ed25519Signer",
    "HmacSha256Signer",
    "IdentityRequiredError",
    "KeyAlreadyCurrentError",
    "LogCoverage",
    "ManifestSigner",
    "ManifestVerificationError",
    "NdjsonAuditSink",
    "QuarantinedLine",
    "RunAlreadySealedError",
    "RunNotPendingError",
    "TeeAuditSink",
    "manifest_hash",
    "quarantine_damaged_lines",
    "rotate_manifest_key",
    "seal_ndjson_runs",
    "seal_run",
    "verify_manifest",
    "verify_ndjson_log",
    "verify_ndjson_log_coverage",
]
