#!/usr/bin/env python3
"""Generate pyproject.toml files from shared configuration.

Usage:
    python scripts/generate_pyproject.py          # Generate all files
    python scripts/generate_pyproject.py --check  # Check if files are up-to-date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[import-not-found,unused-ignore]

CONFIG_DIR = Path("config")
SHARED_CONFIG = CONFIG_DIR / "shared.toml"
PACKAGES_CONFIG = CONFIG_DIR / "packages.toml"
ROOT_PYPROJECT = Path("pyproject.toml")

HEADER = """\
# AUTO-GENERATED by scripts/generate_pyproject.py
# Do not edit directly - modify config/shared.toml or config/packages.toml instead
"""

# Expands to the published packages nested under a package's path. See issue #345.
PUBLISHED_CHILDREN = "{published_children}"

# Expands to [project].version in shared.toml; sibling dependencies must use this instead of a hand-written floor.
VERSION_PLACEHOLDER = "{version}"

# The distribution name a PEP 508 dependency string starts with; placeholders like {core_dependency} match none.
DEP_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")

# A sibling requirement (marker already stripped), spelled exactly '<name>[extras]>={version}'.
SIBLING_FLOOR_RE = re.compile(r"^\s*[A-Za-z0-9][A-Za-z0-9._-]*\s*(?:\[[^\]]*\])?\s*>=\s*\{version\}\s*$")

# Exact-operator variant, spelled '<name>[extras]=={version}'. Required (not merely accepted) for a
# sibling nested under an entry_point_bundle's own path, named in that bundle's own dependencies or a
# non-dev extra: such a requirement makes the bundle own (exclude from its own wheel) that sibling's
# code, which its own distribution ships instead, so the bundle must pin it exactly, on every platform
# (all packages release in lockstep at one version). No environment marker is accepted there either.
SIBLING_EXACT_FLOOR_RE = re.compile(r"^\s*[A-Za-z0-9][A-Za-z0-9._-]*\s*(?:\[[^\]]*\])?\s*==\s*\{version\}\s*$")

# A bare sibling requirement: just the name (and optional extras), no specifier at all.
BARE_SIBLING_RE = re.compile(r"^\s*[A-Za-z0-9][A-Za-z0-9._-]*\s*(?:\[[^\]]*\])?\s*$")

# Companion marker group (not a plugin-type group): declares a package's optional import roots for
# PluginLoader instead of listing plugin classes; not a valid load_entry_points(group=...) argument.
OPTIONAL_DEPENDENCIES_GROUP = "mloda.optional_dependencies"

# Default entry-point target module suffix, exposed once so other scripts never hand-write the literal.
DEFAULT_MODULE_SUFFIX = "manifest"

# Entry-point group -> manifest attribute exposing the concrete plugin classes.
# mloda discovers installed plugins through these entry-point groups; each
# plugin package ships a ``manifest.py`` listing its concrete plugin classes
# under the mapped attribute.
ENTRY_POINT_ATTRS = {
    "mloda.feature_groups": "FEATURE_GROUPS",
    "mloda.compute_frameworks": "COMPUTE_FRAMEWORKS",
    "mloda.extenders": "EXTENDERS",
    OPTIONAL_DEPENDENCIES_GROUP: "OPTIONAL_DEPENDENCIES",
}

# Entry-point group -> target module suffix, default DEFAULT_MODULE_SUFFIX. The optional-dependencies
# marker targets a sibling module that must import cleanly without the optional dependency.
ENTRY_POINT_MODULE_SUFFIX: dict[str, str] = {
    OPTIONAL_DEPENDENCIES_GROUP: "_optional_dependencies",
}


def normalize_package_name(name: str) -> str:
    """PEP 503 normal form: lowercase, runs of '-', '_', '.' collapsed to '-'."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _validate_sibling_spelling(
    pkg_name: str,
    dep: str,
    with_core: str,
    canonical_siblings: set[str],
    allow_bare: bool,
    nested_siblings: set[str] | None = None,
) -> None:
    """Raise if ``with_core`` hand-pins a sibling floor, or misuses {version}.

    A plain sibling dependency must be spelled '<sibling>[extras]>={version}' (bare allowed only in an
    extra). A requirement in ``nested_siblings`` instead owns that sibling (excludes its code from the
    bundle's own wheel), so it must be spelled exactly '<sibling>[extras]=={version}', with no
    environment marker, regardless of ``allow_bare``.
    """
    requirement = with_core.split(";", 1)[0]
    has_marker = ";" in with_core
    match = DEP_NAME_RE.match(requirement)
    sibling_name = normalize_package_name(match.group(1)) if match is not None else None
    is_sibling = sibling_name is not None and sibling_name in canonical_siblings
    owns_nested = is_sibling and nested_siblings is not None and sibling_name in nested_siblings

    if owns_nested:
        if has_marker or SIBLING_EXACT_FLOOR_RE.match(requirement) is None:
            raise ValueError(
                f"{pkg_name}: {dep!r} owns nested sibling {sibling_name!r}, which must be spelled exactly "
                "'<sibling>[extras]=={version}' with no environment marker"
            )
        return

    spelled_as_floor = is_sibling and SIBLING_FLOOR_RE.match(requirement) is not None
    is_bare = allow_bare and BARE_SIBLING_RE.match(requirement) is not None

    if is_sibling and not spelled_as_floor and not is_bare and VERSION_PLACEHOLDER not in with_core:
        raise ValueError(
            f"{pkg_name}: sibling dependency {dep!r} must use the {{version}} placeholder instead of a hand-written floor"
        )

    if VERSION_PLACEHOLDER in with_core and not (spelled_as_floor and with_core.count(VERSION_PLACEHOLDER) == 1):
        message = (
            f"{pkg_name}: dependency {dep!r} uses {{version}} outside a sibling floor "
            "spelled '<sibling>[extras]>={version}'"
        )
        if with_core != dep:
            message += f" (expands to {with_core!r})"
        raise ValueError(message)


def _resolve_dep_list(
    pkg_name: str,
    raw_deps: list[str],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
    allow_bare_sibling: bool,
    nested_siblings: set[str] | None = None,
) -> list[str]:
    """Expand {core_dependency} first, validate sibling spelling on the result, then expand {version}."""
    defaults = shared.get("defaults", {})
    core_dep = defaults.get("core_dependency", "")
    if not core_dep and any("{core_dependency}" in dep for dep in raw_deps):
        raise ValueError(
            f"{pkg_name}: dependency uses {{core_dependency}} placeholder but "
            "[defaults].core_dependency is not set in config/shared.toml"
        )

    version = shared.get("project", {}).get("version")
    if version is None and any(VERSION_PLACEHOLDER in dep for dep in raw_deps):
        raise ValueError(
            f"{pkg_name}: dependency uses {{version}} placeholder but "
            "[project].version is not set in config/shared.toml"
        )

    canonical_siblings = {normalize_package_name(name) for name in all_packages}
    resolved: list[str] = []
    for dep in raw_deps:
        with_core = dep.replace("{core_dependency}", core_dep)
        _validate_sibling_spelling(pkg_name, dep, with_core, canonical_siblings, allow_bare_sibling, nested_siblings)
        expanded = with_core.replace(VERSION_PLACEHOLDER, str(version))
        if "{" in expanded:
            raise ValueError(
                f"{pkg_name}: dependency {dep!r} still contains a placeholder after expansion ({expanded!r})"
            )
        resolved.append(expanded)
    return resolved


def resolve_dependencies(
    pkg_name: str,
    raw_deps: list[str],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
    nested_siblings: set[str] | None = None,
) -> list[str]:
    """Expand {core_dependency} and {version} placeholders in a package's plain ``dependencies``; raises if a
    sibling dependency isn't spelled '<name>[extras]>={version}' (or, for a sibling in ``nested_siblings``,
    the exact-operator '<name>[extras]=={version}')."""
    return _resolve_dep_list(
        pkg_name, raw_deps, shared, all_packages, allow_bare_sibling=False, nested_siblings=nested_siblings
    )


def resolve_optional_dependencies(
    pkg_name: str,
    opt_deps: dict[str, list[str]],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
    nested_siblings: set[str] | None = None,
) -> dict[str, list[str]]:
    """Expand {core_dependency} and {version} placeholders in a package's merged ``optional_dependencies``; a
    sibling entry here may also be bare, unlike plain ``dependencies``' strict '<name>[extras]>={version}'.
    ``nested_siblings`` (bundle ownership, see ``_validate_sibling_spelling``) applies to every group except
    ``dev``: a dev-only dependency never ships, so it cannot own a sibling's code."""
    return {
        group: _resolve_dep_list(
            pkg_name,
            deps,
            shared,
            all_packages,
            allow_bare_sibling=True,
            nested_siblings=None if group == "dev" else nested_siblings,
        )
        for group, deps in opt_deps.items()
    }


def normalize_dependency_name(dep: str) -> str | None:
    """PEP 503 normalize a dependency spec's leading package name, or None if it has no name."""
    match = DEP_NAME_RE.match(dep)
    if not match:
        return None
    return normalize_package_name(match.group(1))


def sibling_dependency_name(
    dep: str,
    all_packages: dict[str, dict[str, Any]],
    configured: dict[str, str] | None = None,
) -> str | None:
    """The configured package name (as spelled in config) one requirement string names, extras and
    markers ignored, or None if it names no configured package. ``configured`` lets a caller looping
    over many requirements build the normalized name lookup once instead of per call."""
    lookup = configured if configured is not None else {normalize_package_name(name): name for name in all_packages}
    match = DEP_NAME_RE.match(dep.split(";", 1)[0])
    if match is None:
        return None
    return lookup.get(normalize_package_name(match.group(1)))


def sibling_dependency_names(deps: list[str], all_packages: dict[str, dict[str, Any]]) -> list[str]:
    """Return the configured package names (as spelled in config) that ``deps`` name, extras and markers ignored."""
    configured = {normalize_package_name(name): name for name in all_packages}
    names: set[str] = set()
    for dep in deps:
        name = sibling_dependency_name(dep, all_packages, configured)
        if name is not None:
            names.add(name)
    return sorted(names)


def nested_package_names(pkg_path: str, all_packages: dict[str, dict[str, Any]]) -> list[str]:
    """Return the configured packages whose path is nested under ``pkg_path``, in config order."""
    prefix = pkg_path.rstrip("/") + "/"
    return [name for name, cfg in all_packages.items() if cfg["path"].startswith(prefix)]


def bundle_owned_names(pkg_config: dict[str, Any], all_packages: dict[str, dict[str, Any]]) -> list[str]:
    """Nested configured packages an entry_point_bundle owns: named in its own ``dependencies`` or a
    non-dev ``optional_dependencies`` extra (parsed like ``sibling_dependency_names``). The owned
    package's own wheel ships it and declares its own entry points. Not a bundle -> ``[]``."""
    if not pkg_config.get("entry_point_bundle"):
        return []
    raw: list[str] = list(pkg_config.get("dependencies", []))
    for extra_name, deps in pkg_config.get("optional_dependencies", {}).items():
        if extra_name != "dev":
            raw.extend(deps)
    owned = set(sibling_dependency_names(raw, all_packages))
    return [name for name in nested_package_names(pkg_config["path"], all_packages) if name in owned]


def skips_default_optional_dependencies(pkg_name: str) -> bool:
    """Whether pkg_name assembles its own optional-dependencies table and skips the shared
    [defaults].optional_dependencies merge."""
    return pkg_name in ("mloda-testing", "mloda-community", "mloda-enterprise")


def _merged_optional_dependencies(
    pkg_name: str,
    pkg_config: dict[str, Any],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> dict[str, list[str]]:
    """A package's own (raw, unresolved) optional_dependencies merged with the shared defaults, honoring
    ``skips_default_optional_dependencies``."""
    default_opt_deps = (
        {}
        if skips_default_optional_dependencies(pkg_name)
        else shared.get("defaults", {}).get("optional_dependencies", {})
    )
    pkg_opt_deps = expand_published_children(pkg_config, all_packages)
    return {**default_opt_deps, **pkg_opt_deps}


def validate_ownership_and_publishing(
    pkg_name: str,
    pkg_config: dict[str, Any],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> None:
    """Raise ValueError for a bundle ownership violation, or a published package's dependency or
    non-dev extra (including one merged in from the shared defaults) naming an unpublished sibling.
    Runs on the raw config before any resolution, so an older, unrelated resolver error cannot mask it.
    """
    raw_opt_deps: dict[str, list[str]] = pkg_config.get("optional_dependencies", {})

    if pkg_config.get("entry_point_bundle"):
        nested = nested_package_names(pkg_config["path"], all_packages)

        for group, deps in raw_opt_deps.items():
            if PUBLISHED_CHILDREN in deps:
                raise ValueError(
                    f"Bundle {pkg_name}: extra {group!r} names the {PUBLISHED_CHILDREN!r} placeholder, "
                    "which is not available in an entry_point_bundle's own extras; name each owned "
                    "nested sibling explicitly, spelled exactly '<sibling>[extras]=={version}'"
                )

        for dep in raw_opt_deps.get("dev", []):
            sibling = sibling_dependency_name(dep, all_packages)
            if sibling is not None and sibling in nested:
                raise ValueError(
                    f"Bundle {pkg_name}: 'dev' extra names {dep!r}, a nested sibling {sibling!r}; the "
                    "'dev' extra must never name a nested sibling package, in any spelling"
                )

        owned = set(bundle_owned_names(pkg_config, all_packages))
        published_nested = {name for name in nested if all_packages[name].get("published")}

        for name in sorted(owned - published_nested):
            raise ValueError(
                f"Bundle {pkg_name} owns nested package {name} (via dependencies or an extra), "
                "which must be published = true"
            )

        for name in sorted(published_nested - owned):
            raise ValueError(
                f"Bundle {pkg_name} does not own published nested package {name}: a bundle must own "
                "exactly its published nested packages, named in its own dependencies or a non-dev "
                "extra, spelled exactly '<sibling>[extras]=={version}'"
            )

        dep_owned = set(sibling_dependency_names(pkg_config.get("dependencies", []), all_packages))
        for owned_name in sorted(owned - dep_owned):
            owned_path = all_packages[owned_name]["path"]
            for child in nested_package_names(owned_path, all_packages):
                if child not in owned:
                    raise ValueError(
                        f"Bundle {pkg_name} owns {owned_name} only through an extra, but does not own "
                        f"{child}, a configured package nested under {owned_name}'s own path; a bundle "
                        "owning a package only through a non-dev extra must also own every configured "
                        "package nested under it"
                    )

    if pkg_config.get("published"):
        merged_opt_deps = _merged_optional_dependencies(pkg_name, pkg_config, shared, all_packages)
        raw_deps = list(pkg_config.get("dependencies", []))
        for group, deps in merged_opt_deps.items():
            if group != "dev":
                raw_deps.extend(deps)
        for dep in raw_deps:
            sibling = sibling_dependency_name(dep, all_packages)
            if sibling is None or all_packages[sibling].get("published"):
                continue
            raise ValueError(
                f"{pkg_name}: dependency {dep!r} names unpublished sibling {sibling!r}; a published "
                "package's dependencies or a non-dev extra must never name an unpublished configured "
                "sibling package"
            )


def compute_wheel_packages(
    pkg_config: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> list[str]:
    """The dotted ``[tool.setuptools] packages`` a package's own generated wheel lists: filesystem
    discovery under the package's path, excluding nested configured packages' own paths (each ships
    its own wheel). An entry_point_bundle instead excludes each owned package's own wheel packages,
    not its whole path, so an unowned package nested under an owned one still ships in the bundle
    wheel. ``py_typed`` adds the package's own dotted path, since that ships the PEP 561 marker for a
    namespace portion discovery alone would miss."""
    if "workspace_deps" in pkg_config:
        return []

    owned_names = bundle_owned_names(pkg_config, all_packages)
    excluded_pkg_names: set[str] = set()
    if not pkg_config.get("entry_point_bundle"):
        excluded_pkg_names |= set(nested_package_names(pkg_config["path"], all_packages))

    exclude_paths = sorted(
        all_packages[dep_name]["path"] for dep_name in excluded_pkg_names if dep_name in all_packages
    )
    packages = discover_packages(pkg_config["path"], exclude_paths)

    if owned_names:
        owned_wheel_packages: set[str] = set()
        for dep_name in owned_names:
            owned_wheel_packages |= set(compute_wheel_packages(all_packages[dep_name], all_packages))
        packages = [p for p in packages if p not in owned_wheel_packages]

    if pkg_config.get("py_typed"):
        dotted_path = pkg_config["path"].replace("/", ".")
        packages = sorted(set(packages) | {dotted_path})

    return packages


def compute_entry_points(
    pkg_name: str,
    pkg_config: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> dict[str, list[tuple[str, str]]]:
    """Compute entry-point tables for a package.

    Returns a mapping of entry-point group -> sorted list of ``(label, value)``
    pairs, where ``value`` is the canonical ``<dotted>.<module_suffix>:<ATTR>`` target
    (``module_suffix`` per ``ENTRY_POINT_MODULE_SUFFIX``, default ``manifest``).

    Bundle packages (``entry_point_bundle = true``) aggregate the entry points of every nested
    plugin package whose path lives under the bundle path, except a package the bundle owns
    (``bundle_owned_names``): that package's own wheel ships it, so its own generated pyproject
    declares its entry points instead. Regular plugin packages emit their own declared
    ``entry_point_groups``.
    """
    if pkg_config.get("entry_point_bundle") and pkg_config.get("entry_point_groups"):
        raise ValueError(f"{pkg_name}: entry_point_bundle and entry_point_groups are mutually exclusive")

    result: dict[str, list[tuple[str, str]]] = {}

    if pkg_config.get("entry_point_bundle"):
        owned = set(bundle_owned_names(pkg_config, all_packages))
        for name in nested_package_names(pkg_config["path"], all_packages):
            if name in owned:
                continue
            cfg = all_packages[name]
            groups = cfg.get("entry_point_groups")
            if not groups:
                continue
            for group in groups:
                module_suffix = ENTRY_POINT_MODULE_SUFFIX.get(group, DEFAULT_MODULE_SUFFIX)
                value = f"{cfg['path'].replace('/', '.')}.{module_suffix}:{ENTRY_POINT_ATTRS[group]}"
                result.setdefault(group, []).append((name, value))
    else:
        for group in pkg_config.get("entry_point_groups", []):
            module_suffix = ENTRY_POINT_MODULE_SUFFIX.get(group, DEFAULT_MODULE_SUFFIX)
            value = f"{pkg_config['path'].replace('/', '.')}.{module_suffix}:{ENTRY_POINT_ATTRS[group]}"
            result.setdefault(group, []).append((pkg_name, value))

    return {group: sorted(pairs, key=lambda pair: pair[0]) for group, pairs in result.items() if pairs}


def expand_published_children(
    pkg_config: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> dict[str, list[str]]:
    """Substitute ``{published_children}`` in a package's optional dependencies, in config order."""
    opt_deps: dict[str, list[str]] = pkg_config.get("optional_dependencies", {})
    if not any(PUBLISHED_CHILDREN in deps for deps in opt_deps.values()):
        return opt_deps

    children = [
        name for name in nested_package_names(pkg_config["path"], all_packages) if all_packages[name].get("published")
    ]

    expanded: dict[str, list[str]] = {}
    for group, deps in opt_deps.items():
        resolved: list[str] = []
        for dep in deps:
            if dep == PUBLISHED_CHILDREN:
                resolved.extend(children)
            else:
                resolved.append(dep)
        expanded[group] = resolved
    return expanded


def quote_toml_basic_string(value: str, *, key: bool = False) -> str:
    """Quote and escape a TOML basic string, preserving safe bare keys."""
    if key and re.fullmatch(r"[A-Za-z0-9_-]+", value):
        return value

    escapes = {
        '"': r"\"",
        "\\": r"\\",
        "\b": r"\b",
        "\t": r"\t",
        "\n": r"\n",
        "\f": r"\f",
        "\r": r"\r",
    }
    escaped = "".join(
        escapes.get(char, f"\\u{ord(char):04X}" if ord(char) < 0x20 or ord(char) == 0x7F else char) for char in value
    )
    return f'"{escaped}"'


def to_toml_list(items: list[str]) -> str:
    """Format a list of TOML basic strings."""
    quoted = [quote_toml_basic_string(item) for item in items]
    return f"[{', '.join(quoted)}]"


def discover_packages(pkg_path: str, exclude_paths: list[str] | None = None) -> list[str]:
    """Discover all Python packages under a path.

    Finds all directories containing __init__.py and returns them
    as dotted package names (e.g., 'mloda.registry', 'mloda.registry.tests').
    Excludes build artifacts, common non-package directories, and paths
    that are configured as separate packages.
    """
    packages: list[str] = []
    base_path = Path(pkg_path)
    # Directories matched by exact name.
    exclude_dirs = {"build", "dist", ".tox", ".venv", "__pycache__", "tests"}
    # Directories matched by suffix, since real egg-info dirs are named
    # "<package>.egg-info" and never match an exact "in pkg_dir.parts" check.
    exclude_suffixes = (".egg-info",)
    exclude_paths = exclude_paths or []

    if not base_path.exists():
        return packages

    # Walk directory tree looking for __init__.py files
    for init_file in base_path.rglob("__init__.py"):
        pkg_dir = init_file.parent
        pkg_dir_str = str(pkg_dir)
        # Skip excluded directories (exact match)
        if any(excluded in pkg_dir.parts for excluded in exclude_dirs):
            continue
        # Skip excluded directories (suffix match, e.g. "<pkg>.egg-info")
        if any(part.endswith(suffix) for part in pkg_dir.parts for suffix in exclude_suffixes):
            continue
        # Skip paths that are configured as separate packages
        if any(pkg_dir_str == excl or pkg_dir_str.startswith(excl + "/") for excl in exclude_paths):
            continue
        # Convert path to dotted package name (relative to repo root, not package root)
        # pkg_path like "mloda/community/feature_groups/example" -> start from "mloda"
        pkg_name = pkg_dir_str.replace("/", ".").replace("\\", ".")
        packages.append(pkg_name)

    return sorted(packages)


def load_configs() -> tuple[dict[str, Any], dict[str, Any]]:
    """Load shared and packages configuration."""
    with open(SHARED_CONFIG, "rb") as f:
        shared = tomllib.load(f)
    with open(PACKAGES_CONFIG, "rb") as f:
        packages = tomllib.load(f)
    return shared, packages


def generate_pyproject(
    pkg_name: str,
    pkg_config: dict[str, Any],
    shared: dict[str, Any],
    all_packages: dict[str, dict[str, Any]],
) -> str:
    """Generate pyproject.toml content for a package."""
    # A meta-package emits packages = [], which no py.typed marker can ride on.
    if "workspace_deps" in pkg_config and "py_typed" in pkg_config:
        raise ValueError(f"{pkg_name}: workspace_deps and py_typed are mutually exclusive")

    validate_ownership_and_publishing(pkg_name, pkg_config, shared, all_packages)

    # Resolved early so a missing version raises this function's own ValueError, not a raw KeyError.
    defaults = shared.get("defaults", {})
    # A bundle's own nested siblings may use the exact-operator '<sibling>[extras]=={version}' spelling.
    nested_siblings = (
        {normalize_package_name(n) for n in nested_package_names(pkg_config["path"], all_packages)}
        if pkg_config.get("entry_point_bundle")
        else None
    )
    deps = resolve_dependencies(pkg_name, pkg_config.get("dependencies", []), shared, all_packages, nested_siblings)
    runtime_deps = list(deps)  # `deps` is rebound by the optional-dependencies loop below

    lines = [HEADER]

    # Build system
    lines.append("[build-system]")
    lines.append(f"requires = {to_toml_list(shared['build-system']['requires'])}")
    lines.append(f"build-backend = {quote_toml_basic_string(shared['build-system']['build-backend'])}")
    lines.append("")

    # Project section
    lines.append("[project]")
    lines.append(f"name = {quote_toml_basic_string(pkg_name)}")
    lines.append(f"version = {quote_toml_basic_string(shared['project']['version'])}")
    lines.append(f"description = {quote_toml_basic_string(pkg_config['description'])}")

    if pkg_config.get("has_readme"):
        lines.append(f"readme = {quote_toml_basic_string('README.md')}")

    # License - infer from path (enterprise = proprietary), or use default
    if pkg_config["path"].startswith("mloda/enterprise"):
        license_val = "LicenseRef-Proprietary"
    else:
        license_val = defaults.get("license", "Apache-2.0")
    lines.append(f"license = {quote_toml_basic_string(license_val)}")

    # Authors - format as inline table
    authors = shared["project"]["authors"]
    author_strs = [
        f"{{ name = {quote_toml_basic_string(a['name'])}, email = {quote_toml_basic_string(a['email'])} }}"
        for a in authors
    ]
    lines.append(f"authors = [{', '.join(author_strs)}]")

    lines.append(f"dependencies = {to_toml_list(deps)}")

    lines.append(f"requires-python = {quote_toml_basic_string(shared['project']['requires-python'])}")
    lines.append("")

    # Optional dependencies - merge defaults with package-specific (skipped for specific packages)
    merged_opt_deps = resolve_optional_dependencies(
        pkg_name,
        _merged_optional_dependencies(pkg_name, pkg_config, shared, all_packages),
        shared,
        all_packages,
        nested_siblings,
    )
    if merged_opt_deps:
        lines.append("[project.optional-dependencies]")
        for group, deps in merged_opt_deps.items():
            lines.append(f"{quote_toml_basic_string(group, key=True)} = {to_toml_list(deps)}")
        lines.append("")

    # URLs
    lines.append("[project.urls]")
    for key, value in shared["project"]["urls"].items():
        lines.append(f"{quote_toml_basic_string(key, key=True)} = {quote_toml_basic_string(value)}")
    lines.append("")

    # Entry points - mloda plugin discovery (issue #271). Emit groups in the
    # stable ENTRY_POINT_ATTRS insertion order; entry-point labels are
    # distribution names containing hyphens, which are valid bare TOML keys.
    entry_points = compute_entry_points(pkg_name, pkg_config, all_packages)
    for group in ENTRY_POINT_ATTRS:
        pairs = entry_points.get(group)
        if not pairs:
            continue
        lines.append(f"[project.entry-points.{quote_toml_basic_string(group, key=True)}]")
        for label, value in pairs:
            lines.append(f"{quote_toml_basic_string(label, key=True)} = {quote_toml_basic_string(value)}")
        lines.append("")

    # Setuptools config - infer meta-package from workspace_deps
    if "workspace_deps" in pkg_config:
        lines.append("[tool.setuptools]")
        lines.append("packages = []")
    else:
        # Calculate relative path from package dir to repo root
        pkg_path = Path(pkg_config["path"])
        depth = len(pkg_path.parts)
        rel_path = "/".join([".."] * depth)

        # Wheel boundaries come from the configured layout, not the released set: see
        # compute_wheel_packages for the discover/exclude logic, shared with the recursive
        # computation of what an owned package's own wheel lists.
        packages = compute_wheel_packages(pkg_config, all_packages)

        # The package-data table below is belt and braces on top of listing the dotted path.
        package_data: list[str] = []
        if pkg_config.get("py_typed"):
            dotted_path = pkg_config["path"].replace("/", ".")
            # Subtable of [tool.setuptools]: must stay after its keys, or they reparent into it.
            package_data = [
                "",
                "[tool.setuptools.package-data]",
                f"{quote_toml_basic_string(dotted_path, key=True)} = {to_toml_list(['py.typed'])}",
            ]

        lines.append("[tool.setuptools]")
        lines.append(f"package-dir = {{{quote_toml_basic_string('', key=True)} = {quote_toml_basic_string(rel_path)}}}")
        lines.append(f"packages = {to_toml_list(packages)}")
        lines.extend(package_data)
    lines.append("")

    # UV sources for workspace deps
    # Also add mloda-testing for top-level packages that get it from defaults
    pkg_path = Path(pkg_config["path"])
    depth = len(pkg_path.parts)
    gets_default_dev_deps = not skips_default_optional_dependencies(pkg_name)

    if "workspace_deps" in pkg_config:
        lines.append("[tool.uv.sources]")
        for dep in pkg_config["workspace_deps"]:
            lines.append(f"{quote_toml_basic_string(dep, key=True)} = {{ workspace = true }}")
        lines.append("")
    elif depth <= 2:
        # uv resolves a workspace dependency of a top-level member, runtime or extra, only through a source entry.
        extra_deps = [dep for group_deps in merged_opt_deps.values() for dep in group_deps]
        source_names = set(sibling_dependency_names([*runtime_deps, *extra_deps], all_packages))
        if gets_default_dev_deps:
            source_names.add("mloda-testing")
        if source_names:
            lines.append("[tool.uv.sources]")
            for source_name in sorted(source_names):
                lines.append(f"{quote_toml_basic_string(source_name, key=True)} = {{ workspace = true }}")
            lines.append("")

    return "\n".join(lines)


def get_pyproject_path(pkg_config: dict[str, Any]) -> Path:
    """Get the pyproject.toml path for a package."""
    return Path(pkg_config["path"]) / "pyproject.toml"


def generate_workspace_members(packages: dict[str, Any]) -> str:
    """Generate the workspace members TOML section."""
    members = sorted(pkg["path"] for pkg in packages.values())
    lines = [
        "# AUTO-GENERATED workspace members from config/packages.toml",
        "# Do not edit manually - run: python scripts/generate_pyproject.py",
        "[tool.uv.workspace]",
        "members = [",
    ]
    for member in members:
        lines.append(f"    {quote_toml_basic_string(member)},")
    lines.append("]")
    return "\n".join(lines)


def update_workspace_members(packages: dict[str, Any], check: bool = False) -> tuple[bool, str]:
    """Update or check workspace members in root pyproject.toml.

    The workspace members section is always placed at the bottom of the file.
    Returns (success, message) tuple.
    """
    if not ROOT_PYPROJECT.exists():
        return False, f"{ROOT_PYPROJECT}: missing"

    content = ROOT_PYPROJECT.read_text()
    expected_section = generate_workspace_members(packages)

    # Pattern to match [tool.uv.workspace] section (with optional comment header)
    # Only match 1-2 preceding newlines to avoid eating content from previous sections
    pattern = r'\n{1,2}(?:# AUTO-GENERATED workspace members[^\n]*\n# Do not edit manually[^\n]*\n)?\[tool\.uv\.workspace\]\nmembers = \[\n(?:    "(?:[^"\\]|\\.)*",\n)*\]\n?'

    match = re.search(pattern, content)

    if match:
        current_section = match.group(0).strip()
        is_at_end = match.end() >= len(content.rstrip())
        content_matches = current_section == expected_section

        if content_matches and is_at_end:
            return True, "up-to-date"

        if check:
            if not content_matches:
                return False, f"{ROOT_PYPROJECT}: workspace members out of date"
            else:
                return False, f"{ROOT_PYPROJECT}: workspace members not at end of file"

        # Remove existing section and append to bottom
        content_without = content[: match.start()] + content[match.end() :]
        content_without = content_without.rstrip() + "\n\n"
        new_content = content_without + expected_section + "\n"
    else:
        if check:
            return False, f"{ROOT_PYPROJECT}: [tool.uv.workspace] section not found"

        # Append to bottom
        new_content = content.rstrip() + "\n\n" + expected_section + "\n"

    ROOT_PYPROJECT.write_text(new_content)
    return True, "updated"


def update_root_core_dependency(shared: dict[str, Any], check: bool = False) -> tuple[bool, str]:
    """Update or check the mloda-core dependency in root pyproject.toml.

    Rewrites the single ``[project].dependencies`` entry whose package name is
    exactly ``mloda`` (never ``mloda-...``) to the shared ``core_dependency``
    value, so the pin lives in one place. Idempotent and byte-stable.
    Returns (success, message) tuple.
    """
    if not ROOT_PYPROJECT.exists():
        return False, f"{ROOT_PYPROJECT}: missing"

    core_dep = shared.get("defaults", {}).get("core_dependency", "")
    if not core_dep:
        return False, f"{ROOT_PYPROJECT}: core_dependency missing from config/shared.toml"

    content = ROOT_PYPROJECT.read_text()

    # Match a dependency array entry for the exact package name ``mloda``
    # followed by a version specifier (``>=``, ``==`` ...). Requiring a version
    # operator excludes ``mloda-...`` names and workspace paths like
    # ``"mloda/community"``. Preserve indentation/quoting so the file is byte-stable.
    pattern = re.compile(r'(?P<indent>[ \t]*)"mloda(?=[<>=!~])[^"]*"')

    def _replace(match: re.Match[str]) -> str:
        return f"{match.group('indent')}{quote_toml_basic_string(core_dep)}"

    new_content, count = pattern.subn(_replace, content)

    if count == 0:
        return False, f"{ROOT_PYPROJECT}: mloda-core dependency entry not found"

    if new_content == content:
        return True, "up-to-date"

    if check:
        return False, f"{ROOT_PYPROJECT}: mloda-core dependency out of date"

    ROOT_PYPROJECT.write_text(new_content)
    return True, "updated"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate pyproject.toml files")
    parser.add_argument("--check", action="store_true", help="Check if files are up-to-date")
    args = parser.parse_args()

    shared, packages_config = load_configs()
    packages = packages_config.get("packages", {})

    errors = []
    updated = []

    for pkg_name, pkg_config in packages.items():
        pyproject_path = get_pyproject_path(pkg_config)
        expected_content = generate_pyproject(pkg_name, pkg_config, shared, packages)

        if args.check:
            if pyproject_path.exists():
                current_content = pyproject_path.read_text()
                if current_content != expected_content:
                    errors.append(f"{pyproject_path}: out of date")
            else:
                errors.append(f"{pyproject_path}: missing")
        else:
            # Ensure parent directory exists
            pyproject_path.parent.mkdir(parents=True, exist_ok=True)
            pyproject_path.write_text(expected_content)
            updated.append(str(pyproject_path))
            print(f"  ✓ {pyproject_path}")

    # Handle workspace members
    workspace_ok, workspace_msg = update_workspace_members(packages, check=args.check)

    # Handle root pyproject.toml mloda-core dependency (single source of truth)
    core_ok, core_msg = update_root_core_dependency(shared, check=args.check)

    if args.check:
        if not workspace_ok:
            errors.append(workspace_msg)
        if not core_ok:
            errors.append(core_msg)
        if errors:
            print("❌ Files out of date:")
            for e in errors:
                print(f"  - {e}")
            print("\nRun 'python scripts/generate_pyproject.py' to regenerate")
            return 1
        print(f"✅ All {len(packages)} pyproject.toml files are up-to-date")
        print("✅ Workspace members are up-to-date")
        print("✅ Root mloda-core dependency is up-to-date")
        return 0

    if not workspace_ok or not core_ok:
        print("❌ Failed to sync root pyproject.toml:")
        if not workspace_ok:
            print(f"  - {workspace_msg}")
        if not core_ok:
            print(f"  - {core_msg}")
        return 1

    if workspace_ok and workspace_msg == "updated":
        print(f"  ✓ {ROOT_PYPROJECT} (workspace members)")

    if core_ok and core_msg == "updated":
        print(f"  ✓ {ROOT_PYPROJECT} (mloda-core dependency)")

    print(f"\n✅ Generated {len(updated)} pyproject.toml files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
